name: Master Branch CI/CD

on:
  push:
    branches: [ master ]

jobs:
  staging-deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout

        uses: actions/checkout@v2

      - name: Deployment

        uses: appleboy/ssh-action@master

        with:

          host: ${{ secrets.SSH_HOST }}

          password: ${{ secrets.SSH_PASSWORD }}

          username: ${{ secrets.SSH_USERNAME }}

          script: |

            sudo bash /usr/local/bin/mjuyelrana.sh
